require 'foursquare2'
require 'pry'

# client = Foursquare2::Client.new(:client_id => "FEYHVUFU4AUHHLTR0T0IFL4MREWZ3EFCGI1IYAHZINN15FJZ", :client_secret => "AMU4LBCIYBAHOPY0DUCYQ3FQ4SC5FD322USVN5ZV54HLX4PY")

# results = client.search_venues(:ll => '36.142064,-86.816086', :query => 'Starbucks')

# places = results.first[1].first["items"]

# places.each do |place|
#   puts place["name"] 
#   puts place["location"]["address"]
#   puts place["location"]["city"]
#   puts place["location"]["state"]
# end


# ["groups",

#  [{"type"=>"places",
#    "name"=>"Places",
#    "items"=>

#     [

#       {"id"=>"4b2afcaaf964a5205bb324e3",
#       "name"=>"Starbucks",
#       "contact"=>
#        {"phone"=>"6153210262",
#         "formattedPhone"=>"(615) 321-0262",
#         "twitter"=>"starbucks"},
#       "location"=>
#        {"address"=>"3005 West End Ave",
#         "lat"=>36.143544,
#         "lng"=>-86.813794,
#         "distance"=>263,
#         "postalCode"=>"37203",
#         "cc"=>"US",
#         "city"=>"Nashville",
#         "state"=>"TN",
#         "country"=>"United States"},
#       "categories"=>
#        [{"id"=>"4bf58dd8d48988d1e0931735",
#          "name"=>"Coffee Shop",
#          "pluralName"=>"Coffee Shops",
#          "shortName"=>"Coffee Shop",
#          "icon"=>"https://ss1.4sqi.net/img/categories/food/coffeeshop.png",
#          "parents"=>["Food"],
#          "primary"=>true}],
#       "verified"=>true,
#       "restricted"=>true,
#       "stats"=>{"checkinsCount"=>11322, "usersCount"=>2856, "tipCount"=>52},
#       "url"=>"http://www.starbucks.com",
#       "likes"=>{"count"=>0, "groups"=>[]},
#       "menu"=>
#        {"type"=>"Menu",
#         "label"=>"Menu",
#         "anchor"=>"View Menu",
#         "url"=>
#          "https://foursquare.com/v/starbucks/4b2afcaaf964a5205bb324e3/menu",
#         "mobileUrl"=>
#          "https://foursquare.com/v/4b2afcaaf964a5205bb324e3/device_menu"},
#       "storeId"=>"9781"},


#      {"id"=>"4b0755dcf964a52030fc22e3",
#       "name"=>"Starbucks",
#       "contact"=>
#        {"phone"=>"6153410093",
#         "formattedPhone"=>"(615) 341-0093",
#         "twitter"=>"starbucks"},
#       "location"=>
#        {"address"=>"2521 West End Ave",
#         "lat"=>36.146171,
#         "lng"=>-86.809053,
#         "distance"=>780,
#         "postalCode"=>"37203",
#         "cc"=>"US",
#         "city"=>"Nashville",
#         "state"=>"TN",
#         "country"=>"United States"},
#       "categories"=>
#        [{"id"=>"4bf58dd8d48988d1e0931735",
#          "name"=>"Coffee Shop",
#          "pluralName"=>"Coffee Shops",
#          "shortName"=>"Coffee Shop",
#          "icon"=>"https://ss1.4sqi.net/img/categories/food/coffeeshop.png",
#          "parents"=>["Food"],
#          "primary"=>true}],
#       "verified"=>true,
#       "restricted"=>true,
#       "stats"=>{"checkinsCount"=>3522, "usersCount"=>1285, "tipCount"=>22},
#       "url"=>"http://www.starbucks.com",
#       "likes"=>{"count"=>0, "groups"=>[]},
#       "menu"=>
#        {"type"=>"Menu",
#         "label"=>"Menu",
#         "anchor"=>"View Menu",
#         "url"=>
#          "https://foursquare.com/v/starbucks/4b0755dcf964a52030fc22e3/menu",
#         "mobileUrl"=>
#          "https://foursquare.com/v/4b0755dcf964a52030fc22e3/device_menu"},
#       "storeId"=>"8356"},


#      {"id"=>"4b05d49ef964a52016e422e3",
#       "name"=>"Starbucks",
#       "contact"=>
#        {"phone"=>"6153409627",
#         "formattedPhone"=>"(615) 340-9627",
#         "twitter"=>"starbucks"},
#       "location"=>
#        {"address"=>"402 21st Ave S",
#         "lat"=>36.146908,
#         "lng"=>-86.799228,
#         "distance"=>1608,
#         "postalCode"=>"37203",
#         "cc"=>"US",
#         "city"=>"Nashville",
#         "state"=>"TN",
#         "country"=>"United States"},
#       "categories"=>
#        [{"id"=>"4bf58dd8d48988d1e0931735",
#          "name"=>"Coffee Shop",
#          "pluralName"=>"Coffee Shops",
#          "shortName"=>"Coffee Shop",
#          "icon"=>"https://ss1.4sqi.net/img/categories/food/coffeeshop.png",
#          "parents"=>["Food"],
#          "primary"=>true}],
#       "verified"=>true,
#       "restricted"=>true,
#       "stats"=>{"checkinsCount"=>12200, "usersCount"=>2875, "tipCount"=>37},
#       "url"=>"http://www.starbucks.com",
#       "likes"=>{"count"=>0, "groups"=>[]},
#       "menu"=>
#        {"type"=>"Menu",
#         "label"=>"Menu",
#         "anchor"=>"View Menu",
#         "url"=>
#          "https://foursquare.com/v/starbucks/4b05d49ef964a52016e422e3/menu",
#         "mobileUrl"=>
#          "https://foursquare.com/v/4b05d49ef964a52016e422e3/device_menu"},
#       "storeId"=>"8300"},
#      {"id"=>"4b21ab73f964a520d83f24e3",
#       "name"=>"Starbucks",
#       "contact"=>
#        {"phone"=>"6153830353",
#         "formattedPhone"=>"(615) 383-0353",
#         "twitter"=>"starbucks"},
#       "location"=>
#        {"address"=>"3706 Hillsboro Pike",
#         "lat"=>36.109906,
#         "lng"=>-86.81107,
#         "distance"=>3608,
#         "postalCode"=>"37215",
#         "cc"=>"US",
#         "city"=>"Nashville",
#         "state"=>"TN",
#         "country"=>"United States"},
#       "categories"=>
#        [{"id"=>"4bf58dd8d48988d1e0931735",
#          "name"=>"Coffee Shop",
#          "pluralName"=>"Coffee Shops",
#          "shortName"=>"Coffee Shop",
#          "icon"=>"https://ss1.4sqi.net/img/categories/food/coffeeshop.png",
#          "parents"=>["Food"],
#          "primary"=>true}],
#       "verified"=>true,
#       "restricted"=>true,
#       "stats"=>{"checkinsCount"=>6108, "usersCount"=>2029, "tipCount"=>30},
#       "url"=>"http://www.starbucks.com",
#       "likes"=>{"count"=>0, "groups"=>[]},
#       "menu"=>
#        {"type"=>"Menu",
#         "label"=>"Menu",
#         "anchor"=>"View Menu",
#         "url"=>
#          "https://foursquare.com/v/starbucks/4b21ab73f964a520d83f24e3/menu",
#         "mobileUrl"=>
#          "https://foursquare.com/v/4b21ab73f964a520d83f24e3/device_menu"},
#       "storeId"=>"8317"},
#      {"id"=>"4e4dce38bd41b76bef9363e2",
#       "name"=>"Starbucks",
#       "contact"=>{"phone"=>"7706426117", "formattedPhone"=>"(770) 642-6117"},
#       "location"=>
#        {"address"=>"4220 Harding Pike",
#         "lat"=>36.124978084192335,
#         "lng"=>-86.84867200733713,
#         "distance"=>3492,
#         "postalCode"=>"37205",
#         "cc"=>"US",
#         "city"=>"Nashville",
#         "state"=>"TN",
#         "country"=>"United States"},
#       "categories"=>
#        [{"id"=>"4bf58dd8d48988d1e0931735",
#          "name"=>"Coffee Shop",
#          "pluralName"=>"Coffee Shops",
#          "shortName"=>"Coffee Shop",
#          "icon"=>"https://ss1.4sqi.net/img/categories/food/coffeeshop.png",
#          "parents"=>["Food"],
#          "primary"=>true}],
#       "verified"=>false,
#       "restricted"=>true,
#       "stats"=>{"checkinsCount"=>2232, "usersCount"=>630, "tipCount"=>15},
#       "likes"=>{"count"=>0, "groups"=>[]},
#       "menu"=>
#        {"type"=>"Menu",
#         "label"=>"Menu",
#         "anchor"=>"View Menu",
#         "url"=>
#          "https://foursquare.com/v/starbucks-nashville-tn/4e4dce38bd41b76bef9363e2/menu",
#         "mobileUrl"=>
#          "https://foursquare.com/v/4e4dce38bd41b76bef9363e2/device_menu"}},
#      {"id"=>"4ba2e9d5f964a520342238e3",
#       "name"=>"Starbucks",
#       "contact"=>{"phone"=>"6153228996", "formattedPhone"=>"(615) 322-8996"},
#       "location"=>
#        {"address"=>"310 25th Ave S",
#         "crossStreet"=>"In Branscomb - Vanderbilt Student Life Center",
#         "lat"=>36.14432290798661,
#         "lng"=>-86.8053096048711,
#         "distance"=>1000,
#         "postalCode"=>"37240",
#         "cc"=>"US",
#         "city"=>"Nashville",
#         "state"=>"TN",
#         "country"=>"United States"},
#       "categories"=>
#        [{"id"=>"4bf58dd8d48988d1e0931735",
#          "name"=>"Coffee Shop",
#          "pluralName"=>"Coffee Shops",
#          "shortName"=>"Coffee Shop",
#          "icon"=>"https://ss1.4sqi.net/img/categories/food/coffeeshop.png",
#          "parents"=>["Food"],
#          "primary"=>true}],
#       "verified"=>false,
#       "restricted"=>true,
#       "stats"=>{"checkinsCount"=>213, "usersCount"=>89, "tipCount"=>2},
#       "likes"=>{"count"=>0, "groups"=>[]}},
#      {"id"=>"4b057856f964a520925822e3",
#       "name"=>"Starbucks",
#       "contact"=>
#        {"phone"=>"6152483339",
#         "formattedPhone"=>"(615) 248-3339",
#         "twitter"=>"starbucks"},
#       "location"=>
#        {"address"=>"424 Church St Ste 110",
#         "lat"=>36.163646,
#         "lng"=>-86.780073,
#         "distance"=>4031,
#         "postalCode"=>"37219",
#         "cc"=>"US",
#         "city"=>"Nashville",
#         "state"=>"TN",
#         "country"=>"United States"},
#       "categories"=>
#        [{"id"=>"4bf58dd8d48988d1e0931735",
#          "name"=>"Coffee Shop",
#          "pluralName"=>"Coffee Shops",
#          "shortName"=>"Coffee Shop",
#          "icon"=>"https://ss1.4sqi.net/img/categories/food/coffeeshop.png",
#          "parents"=>["Food"],
#          "primary"=>true}],
#       "verified"=>true,
#       "restricted"=>true,
#       "stats"=>{"checkinsCount"=>2936, "usersCount"=>904, "tipCount"=>6},
#       "url"=>"http://www.starbucks.com",
#       "likes"=>{"count"=>0, "groups"=>[]},
#       "menu"=>
#        {"type"=>"Menu",
#         "label"=>"Menu",
#         "anchor"=>"View Menu",
#         "url"=>
#          "https://foursquare.com/v/starbucks/4b057856f964a520925822e3/menu",
#         "mobileUrl"=>
#          "https://foursquare.com/v/4b057856f964a520925822e3/device_menu"},
#       "storeId"=>"8414"},
#      {"id"=>"4b4b2239f964a520d99226e3",
#       "name"=>"Starbucks",
#       "contact"=>
#        {"phone"=>"6157702706",
#         "formattedPhone"=>"(615) 770-2706",
#         "twitter"=>"starbucks"},
#       "location"=>
#        {"address"=>"515 Dominican Dr",
#         "lat"=>36.187712,
#         "lng"=>-86.797832,
#         "distance"=>5339,
#         "postalCode"=>"37228",
#         "cc"=>"US",
#         "city"=>"Nashville",
#         "state"=>"TN",
#         "country"=>"United States"},
#       "categories"=>
#        [{"id"=>"4bf58dd8d48988d1e0931735",
#          "name"=>"Coffee Shop",
#          "pluralName"=>"Coffee Shops",
#          "shortName"=>"Coffee Shop",
#          "icon"=>"https://ss1.4sqi.net/img/categories/food/coffeeshop.png",
#          "parents"=>["Food"],
#          "primary"=>true}],
#       "verified"=>true,
#       "restricted"=>true,
#       "stats"=>{"checkinsCount"=>4806, "usersCount"=>1295, "tipCount"=>31},
#       "url"=>"http://www.starbucks.com",
#       "likes"=>{"count"=>0, "groups"=>[]},
#       "menu"=>
#        {"type"=>"Menu",
#         "label"=>"Menu",
#         "anchor"=>"View Menu",
#         "url"=>
#          "https://foursquare.com/v/starbucks/4b4b2239f964a520d99226e3/menu",
#         "mobileUrl"=>
#          "https://foursquare.com/v/4b4b2239f964a520d99226e3/device_menu"},
#       "storeId"=>"11204"},
#      {"id"=>"4b28eb1df964a5202c9624e3",
#       "name"=>"Starbucks",
#       "contact"=>{"twitter"=>"starbucks"},
#       "location"=>
#        {"address"=>"611 Commerce St",
#         "lat"=>36.160835,
#         "lng"=>-86.78081,
#         "distance"=>3797,
#         "postalCode"=>"37203",
#         "cc"=>"US",
#         "city"=>"Nashville",
#         "state"=>"TN",
#         "country"=>"United States"},
#       "categories"=>
#        [{"id"=>"4bf58dd8d48988d1e0931735",
#          "name"=>"Coffee Shop",
#          "pluralName"=>"Coffee Shops",
#          "shortName"=>"Coffee Shop",
#          "icon"=>"https://ss1.4sqi.net/img/categories/food/coffeeshop.png",
#          "parents"=>["Food"],
#          "primary"=>true}],
#       "verified"=>true,
#       "restricted"=>true,
#       "stats"=>{"checkinsCount"=>1317, "usersCount"=>633, "tipCount"=>8},
#       "url"=>"http://www.starbucks.com",
#       "likes"=>{"count"=>0, "groups"=>[]},
#       "storeId"=>"78012"},
#      {"id"=>"4ee0b01cd3e38ddb2ae93495",
#       "name"=>"Starbucks",
#       "contact"=>
#        {"phone"=>"6157474836",
#         "formattedPhone"=>"(615) 747-4836",
#         "twitter"=>"starbucks"},
#       "location"=>
#        {"address"=>"315 4th Ave N",
#         "lat"=>36.165203143096605,
#         "lng"=>-86.7803580968765,
#         "distance"=>4116,
#         "postalCode"=>"37219",
#         "cc"=>"US",
#         "city"=>"Nashville",
#         "state"=>"TN",
#         "country"=>"United States"},
#       "categories"=>
#        [{"id"=>"4bf58dd8d48988d1e0931735",
#          "name"=>"Coffee Shop",
#          "pluralName"=>"Coffee Shops",
#          "shortName"=>"Coffee Shop",
#          "icon"=>"https://ss1.4sqi.net/img/categories/food/coffeeshop.png",
#          "parents"=>["Food"],
#          "primary"=>true}],
#       "verified"=>true,
#       "restricted"=>true,
#       "stats"=>{"checkinsCount"=>591, "usersCount"=>280, "tipCount"=>6},
#       "url"=>"http://www.starbucks.com",
#       "likes"=>{"count"=>0, "groups"=>[]},
#       "storeId"=>"75791"},
#      {"id"=>"4ba13083f964a52066a037e3",
#       "name"=>"Starbucks",
#       "contact"=>
#        {"phone"=>"6153528461",
#         "formattedPhone"=>"(615) 352-8461",
#         "twitter"=>"starbucks"},
#       "location"=>
#        {"address"=>"26 White Bridge Rd",
#         "lat"=>36.130714,
#         "lng"=>-86.854287,
#         "distance"=>3659,
#         "postalCode"=>"37205",
#         "cc"=>"US",
#         "city"=>"Nashville",
#         "state"=>"TN",
#         "country"=>"United States"},
#       "categories"=>
#        [{"id"=>"4bf58dd8d48988d1e0931735",
#          "name"=>"Coffee Shop",
#          "pluralName"=>"Coffee Shops",
#          "shortName"=>"Coffee Shop",
#          "icon"=>"https://ss1.4sqi.net/img/categories/food/coffeeshop.png",
#          "parents"=>["Food"],
#          "primary"=>true}],
#       "verified"=>true,
#       "restricted"=>true,
#       "stats"=>{"checkinsCount"=>697, "usersCount"=>247, "tipCount"=>3},
#       "url"=>"http://www.starbucks.com",
#       "likes"=>{"count"=>0, "groups"=>[]},
#       "menu"=>
#        {"type"=>"Menu",
#         "label"=>"Menu",
#         "anchor"=>"View Menu",
#         "url"=>
#          "https://foursquare.com/v/starbucks/4ba13083f964a52066a037e3/menu",
#         "mobileUrl"=>
#          "https://foursquare.com/v/4ba13083f964a52066a037e3/device_menu"},
#       "storeId"=>"76524"},
#      {"id"=>"4b79b4f4f964a5207a0c2fe3",
#       "name"=>"Starbucks",
#       "contact"=>{"twitter"=>"starbucks"},
#       "location"=>
#        {"address"=>"3901 Granny White Pike",
#         "lat"=>36.105589,
#         "lng"=>-86.798058,
#         "distance"=>4371,
#         "postalCode"=>"37204",
#         "cc"=>"US",
#         "city"=>"Nashville",
#         "state"=>"TN",
#         "country"=>"United States"},
#       "categories"=>
#        [{"id"=>"4bf58dd8d48988d1e0931735",
#          "name"=>"Coffee Shop",
#          "pluralName"=>"Coffee Shops",
#          "shortName"=>"Coffee Shop",
#          "icon"=>"https://ss1.4sqi.net/img/categories/food/coffeeshop.png",
#          "parents"=>["Food"],
#          "primary"=>true}],
#       "verified"=>true,
#       "restricted"=>true,
#       "stats"=>{"checkinsCount"=>1095, "usersCount"=>258, "tipCount"=>7},
#       "url"=>"http://www.starbucks.com",
#       "likes"=>{"count"=>0, "groups"=>[]},
#       "storeId"=>"75459"},
#      {"id"=>"4bead80561aca593253c8400",
#       "name"=>"Starbucks",
#       "contact"=>
#        {"phone"=>"6152922497",
#         "formattedPhone"=>"(615) 292-2497",
#         "twitter"=>"starbucks"},
#       "location"=>
#        {"address"=>"4416 Ridgefield Way",
#         "lat"=>36.126174,
#         "lng"=>-86.844967,
#         "distance"=>3141,
#         "postalCode"=>"37205",
#         "cc"=>"US",
#         "city"=>"Nashville",
#         "state"=>"TN",
#         "country"=>"United States"},
#       "categories"=>
#        [{"id"=>"4bf58dd8d48988d1e0931735",
#          "name"=>"Coffee Shop",
#          "pluralName"=>"Coffee Shops",
#          "shortName"=>"Coffee Shop",
#          "icon"=>"https://ss1.4sqi.net/img/categories/food/coffeeshop.png",
#          "parents"=>["Food"],
#          "primary"=>true}],
#       "verified"=>true,
#       "restricted"=>true,
#       "stats"=>{"checkinsCount"=>247, "usersCount"=>74, "tipCount"=>1},
#       "url"=>"http://www.starbucks.com",
#       "likes"=>{"count"=>0, "groups"=>[]},
#       "storeId"=>"3743"},
#      {"id"=>"4e29c00b18a80bb05845795c",
#       "name"=>"Starbucks",
#       "contact"=>{},
#       "location"=>
#        {"lat"=>36.10823614029296,
#         "lng"=>-86.82693436235002,
#         "distance"=>3889,
#         "cc"=>"US",
#         "country"=>"United States"},
#       "categories"=>
#        [{"id"=>"4bf58dd8d48988d16d941735",
#          "name"=>"Café",
#          "pluralName"=>"Cafés",
#          "shortName"=>"Café",
#          "icon"=>"https://ss1.4sqi.net/img/categories/food/cafe.png",
#          "parents"=>["Food"],
#          "primary"=>true}],
#       "verified"=>false,
#       "restricted"=>true,
#       "stats"=>{"checkinsCount"=>73, "usersCount"=>53, "tipCount"=>0},
#       "likes"=>{"count"=>0, "groups"=>[]}},
#      {"id"=>"4bbd1463a8cf76b06b61b1fd",
#       "name"=>"Starbucks",
#       "contact"=>
#        {"phone"=>"6154601152",
#         "formattedPhone"=>"(615) 460-1152",
#         "twitter"=>"starbucks"},
#       "location"=>
#        {"address"=>"4514 Harding Pike",
#         "lat"=>36.124849,
#         "lng"=>-86.849191,
#         "distance"=>3539,
#         "postalCode"=>"37205",
#         "cc"=>"US",
#         "city"=>"Nashville",
#         "state"=>"TN",
#         "country"=>"United States"},
#       "categories"=>
#        [{"id"=>"4bf58dd8d48988d1e0931735",
#          "name"=>"Coffee Shop",
#          "pluralName"=>"Coffee Shops",
#          "shortName"=>"Coffee Shop",
#          "icon"=>"https://ss1.4sqi.net/img/categories/food/coffeeshop.png",
#          "parents"=>["Food"],
#          "primary"=>true}],
#       "verified"=>true,
#       "restricted"=>true,
#       "stats"=>{"checkinsCount"=>2390, "usersCount"=>672, "tipCount"=>11},
#       "url"=>"http://www.starbucks.com",
#       "likes"=>{"count"=>0, "groups"=>[]},
#       "menu"=>
#        {"type"=>"Menu",
#         "label"=>"Menu",
#         "anchor"=>"View Menu",
#         "url"=>
#          "https://foursquare.com/v/starbucks/4bbd1463a8cf76b06b61b1fd/menu",
#         "mobileUrl"=>
#          "https://foursquare.com/v/4bbd1463a8cf76b06b61b1fd/device_menu"},
#       "storeId"=>"8403"},
#      {"id"=>"52869069498e3289da674f38",
#       "name"=>"Starbucks",
#       "contact"=>
#        {"phone"=>"6157832844",
#         "formattedPhone"=>"(615) 783-2844",
#         "twitter"=>"starbucks"},
#       "location"=>
#        {"address"=>"2153 Green Hills Village Drive",
#         "lat"=>36.10780185314908,
#         "lng"=>-86.81540235502598,
#         "distance"=>3814,
#         "postalCode"=>"37215",
#         "cc"=>"US",
#         "city"=>"Nashville",
#         "state"=>"TN",
#         "country"=>"United States"},
#       "categories"=>
#        [{"id"=>"4bf58dd8d48988d1e0931735",
#          "name"=>"Coffee Shop",
#          "pluralName"=>"Coffee Shops",
#          "shortName"=>"Coffee Shop",
#          "icon"=>"https://ss1.4sqi.net/img/categories/food/coffeeshop.png",
#          "parents"=>["Food"],
#          "primary"=>true}],
#       "verified"=>false,
#       "restricted"=>true,
#       "stats"=>{"checkinsCount"=>3490, "usersCount"=>1559, "tipCount"=>9},
#       "url"=>"http://www.starbucks.com",
#       "likes"=>{"count"=>0, "groups"=>[]},
#       "menu"=>
#        {"type"=>"Menu",
#         "label"=>"Menu",
#         "anchor"=>"View Menu",
#         "url"=>
#          "https://foursquare.com/v/starbucks/52869069498e3289da674f38/menu",
#         "mobileUrl"=>
#          "https://foursquare.com/v/52869069498e3289da674f38/device_menu"},
#       "storeId"=>"8415"},
#      {"id"=>"4f1b2317e4b044fd353b2388",
#       "name"=>"Starbucks",
#       "contact"=>{},
#       "location"=>
#        {"lat"=>36.12530794009897,
#         "lng"=>-86.8537680392669,
#         "distance"=>3867,
#         "postalCode"=>"37205",
#         "cc"=>"US",
#         "city"=>"Nashville",
#         "state"=>"TN",
#         "country"=>"United States"},
#       "categories"=>
#        [{"id"=>"4bf58dd8d48988d1e0931735",
#          "name"=>"Coffee Shop",
#          "pluralName"=>"Coffee Shops",
#          "shortName"=>"Coffee Shop",
#          "icon"=>"https://ss1.4sqi.net/img/categories/food/coffeeshop.png",
#          "parents"=>["Food"],
#          "primary"=>true}],
#       "verified"=>false,
#       "restricted"=>true,
#       "stats"=>{"checkinsCount"=>44, "usersCount"=>31, "tipCount"=>0},
#       "likes"=>{"count"=>0, "groups"=>[]}},
#      {"id"=>"4b09f9d7f964a520a62023e3",
#       "name"=>"Starbucks",
#       "contact"=>
#        {"phone"=>"6152977531",
#         "formattedPhone"=>"(615) 297-7531",
#         "twitter"=>"starbucks"},
#       "location"=>
#        {"address"=>"2131 Abbott Martin Rd",
#         "lat"=>36.105989,
#         "lng"=>-86.818438,
#         "distance"=>4021,
#         "postalCode"=>"37215",
#         "cc"=>"US",
#         "city"=>"Nashville",
#         "state"=>"TN",
#         "country"=>"United States"},
#       "categories"=>
#        [{"id"=>"4bf58dd8d48988d1e0931735",
#          "name"=>"Coffee Shop",
#          "pluralName"=>"Coffee Shops",
#          "shortName"=>"Coffee Shop",
#          "icon"=>"https://ss1.4sqi.net/img/categories/food/coffeeshop.png",
#          "parents"=>["Food"],
#          "primary"=>true}],
#       "verified"=>true,
#       "restricted"=>true,
#       "stats"=>{"checkinsCount"=>312, "usersCount"=>185, "tipCount"=>3},
#       "url"=>"http://www.starbucks.com",
#       "likes"=>{"count"=>0, "groups"=>[]},
#       "storeId"=>"79223"},
#      {"id"=>"4ba12f5cf964a520fd9f37e3",
#       "name"=>"Starbucks",
#       "contact"=>
#        {"phone"=>"6158856671",
#         "formattedPhone"=>"(615) 885-6671",
#         "twitter"=>"starbucks"},
#       "location"=>
#        {"address"=>"3814 Charlotte Ave",
#         "lat"=>36.134444,
#         "lng"=>-86.89218,
#         "distance"=>6893,
#         "postalCode"=>"37209",
#         "cc"=>"US",
#         "city"=>"Nashville",
#         "state"=>"TN",
#         "country"=>"United States"},
#       "categories"=>
#        [{"id"=>"4bf58dd8d48988d1e0931735",
#          "name"=>"Coffee Shop",
#          "pluralName"=>"Coffee Shops",
#          "shortName"=>"Coffee Shop",
#          "icon"=>"https://ss1.4sqi.net/img/categories/food/coffeeshop.png",
#          "parents"=>["Food"],
#          "primary"=>true}],
#       "verified"=>true,
#       "restricted"=>true,
#       "stats"=>{"checkinsCount"=>791, "usersCount"=>358, "tipCount"=>2},
#       "url"=>"http://www.starbucks.com",
#       "likes"=>{"count"=>0, "groups"=>[]},
#       "storeId"=>"76738"},
#      {"id"=>"51a8c6d5498e18fd00d9c4e3",
#       "name"=>"starbucks VA Hospital",
#       "contact"=>{},
#       "location"=>
#        {"address"=>"24th Ave",
#         "crossStreet"=>"Broadway",
#         "lat"=>36.13782467831609,
#         "lng"=>-86.80541750734297,
#         "distance"=>1068,
#         "cc"=>"US",
#         "city"=>"Nashville",
#         "state"=>"TN",
#         "country"=>"United States"},
#       "categories"=>
#        [{"id"=>"4bf58dd8d48988d1e0931735",
#          "name"=>"Coffee Shop",
#          "pluralName"=>"Coffee Shops",
#          "shortName"=>"Coffee Shop",
#          "icon"=>"https://ss1.4sqi.net/img/categories/food/coffeeshop.png",
#          "parents"=>["Food"],
#          "primary"=>true}],
#       "verified"=>false,
#       "restricted"=>true,
#       "stats"=>{"checkinsCount"=>8, "usersCount"=>3, "tipCount"=>0},
#       "likes"=>{"count"=>0, "groups"=>[]}},
#      {"id"=>"50549491e4b0978a0f6eee38",
#       "name"=>"Starbucks",
#       "contact"=>{"phone"=>"6158864542", "formattedPhone"=>"(615) 886-4542"},
#       "location"=>
#        {"address"=>"Opry Mills",
#         "lat"=>36.20255714224756,
#         "lng"=>-86.69269133418967,
#         "distance"=>12973,
#         "postalCode"=>"37214",
#         "cc"=>"US",
#         "city"=>"Nashville",
#         "state"=>"TN",
#         "country"=>"United States"},
#       "categories"=>
#        [{"id"=>"4bf58dd8d48988d1e0931735",
#          "name"=>"Coffee Shop",
#          "pluralName"=>"Coffee Shops",
#          "shortName"=>"Coffee Shop",
#          "icon"=>"https://ss1.4sqi.net/img/categories/food/coffeeshop.png",
#          "parents"=>["Food"],
#          "primary"=>true}],
#       "verified"=>false,
#       "restricted"=>true,
#       "stats"=>{"checkinsCount"=>759, "usersCount"=>464, "tipCount"=>8},
#       "likes"=>{"count"=>0, "groups"=>[]}},
#      {"id"=>"4b098898f964a520f31823e3",
#       "name"=>"Starbucks",
#       "contact"=>
#        {"phone"=>"6153719699",
#         "formattedPhone"=>"(615) 371-9699",
#         "twitter"=>"starbucks"},
#       "location"=>
#        {"address"=>"198 Westpark Drive",
#         "lat"=>36.036913,
#         "lng"=>-86.801263,
#         "distance"=>11780,
#         "postalCode"=>"37027",
#         "cc"=>"US",
#         "city"=>"Brentwood",
#         "state"=>"TN",
#         "country"=>"United States"},
#       "categories"=>
#        [{"id"=>"4bf58dd8d48988d1e0931735",
#          "name"=>"Coffee Shop",
#          "pluralName"=>"Coffee Shops",
#          "shortName"=>"Coffee Shop",
#          "icon"=>"https://ss1.4sqi.net/img/categories/food/coffeeshop.png",
#          "parents"=>["Food"],
#          "primary"=>true}],
#       "verified"=>true,
#       "restricted"=>true,
#       "stats"=>{"checkinsCount"=>5376, "usersCount"=>1220, "tipCount"=>21},
#       "url"=>"http://www.starbucks.com",
#       "likes"=>{"count"=>0, "groups"=>[]},
#       "menu"=>
#        {"type"=>"Menu",
#         "label"=>"Menu",
#         "anchor"=>"View Menu",
#         "url"=>
#          "https://foursquare.com/v/starbucks/4b098898f964a520f31823e3/menu",
#         "mobileUrl"=>
#          "https://foursquare.com/v/4b098898f964a520f31823e3/device_menu"},
#       "storeId"=>"9778"},
#      {"id"=>"4b534012f964a5201e9427e3",
#       "name"=>"Starbucks",
#       "contact"=>
#        {"phone"=>"6156730235",
#         "formattedPhone"=>"(615) 673-0235",
#         "twitter"=>"starbucks"},
#       "location"=>
#        {"address"=>"7083 Highway 70 S",
#         "lat"=>36.074449,
#         "lng"=>-86.920475,
#         "distance"=>12032,
#         "postalCode"=>"37221",
#         "cc"=>"US",
#         "city"=>"Nashville",
#         "state"=>"TN",
#         "country"=>"United States"},
#       "categories"=>
#        [{"id"=>"4bf58dd8d48988d1e0931735",
#          "name"=>"Coffee Shop",
#          "pluralName"=>"Coffee Shops",
#          "shortName"=>"Coffee Shop",
#          "icon"=>"https://ss1.4sqi.net/img/categories/food/coffeeshop.png",
#          "parents"=>["Food"],
#          "primary"=>true}],
#       "verified"=>true,
#       "restricted"=>true,
#       "stats"=>{"checkinsCount"=>4713, "usersCount"=>783, "tipCount"=>12},
#       "url"=>"http://www.starbucks.com",
#       "likes"=>{"count"=>0, "groups"=>[]},
#       "menu"=>
#        {"type"=>"Menu",
#         "label"=>"Menu",
#         "anchor"=>"View Menu",
#         "url"=>
#          "https://foursquare.com/v/starbucks/4b534012f964a5201e9427e3/menu",
#         "mobileUrl"=>
#          "https://foursquare.com/v/4b534012f964a5201e9427e3/device_menu"},
#       "storeId"=>"8525"},
#      {"id"=>"4e5bb1751495a891129b947b",
#       "name"=>"Starbucks",
#       "contact"=>{},
#       "location"=>
#        {"address"=>"600 Marriott Dr",
#         "crossStreet"=>"Inside Marriott Hotel",
#         "lat"=>36.146121550176886,
#         "lng"=>-86.69258318259398,
#         "distance"=>11111,
#         "postalCode"=>"37210",
#         "cc"=>"US",
#         "city"=>"Nashville",
#         "state"=>"TN",
#         "country"=>"United States"},
#       "categories"=>
#        [{"id"=>"4bf58dd8d48988d1e0931735",
#          "name"=>"Coffee Shop",
#          "pluralName"=>"Coffee Shops",
#          "shortName"=>"Coffee Shop",
#          "icon"=>"https://ss1.4sqi.net/img/categories/food/coffeeshop.png",
#          "parents"=>["Food"],
#          "primary"=>true}],
#       "verified"=>false,
#       "restricted"=>true,
#       "stats"=>{"checkinsCount"=>423, "usersCount"=>153, "tipCount"=>0},
#       "likes"=>{"count"=>0, "groups"=>[]}},
#      {"id"=>"4f322e7219836c91c7be2670",
#       "name"=>"Starbucks Coffee",
#       "contact"=>{"phone"=>"6158856671", "formattedPhone"=>"(615) 885-6671"},
#       "location"=>
#        {"address"=>"3814 Charlotte Ave",
#         "lat"=>36.15345,
#         "lng"=>-86.832311,
#         "distance"=>1932,
#         "cc"=>"US",
#         "city"=>"Nashville",
#         "state"=>"TN",
#         "country"=>"United States"},
#       "categories"=>
#        [{"id"=>"4bf58dd8d48988d1e0931735",
#          "name"=>"Coffee Shop",
#          "pluralName"=>"Coffee Shops",
#          "shortName"=>"Coffee Shop",
#          "icon"=>"https://ss1.4sqi.net/img/categories/food/coffeeshop.png",
#          "parents"=>["Food"],
#          "primary"=>true}],
#       "verified"=>false,
#       "restricted"=>true,
#       "stats"=>{"checkinsCount"=>0, "usersCount"=>0, "tipCount"=>0},
#       "url"=>"http://www.starbucks.com",
#       "likes"=>{"count"=>0, "groups"=>[]}},
#      {"id"=>"4f68a39ee4b0b0f93cef9f0d",
#       "name"=>"Starbucks in St. Thomas",
#       "contact"=>{},
#       "location"=>
#        {"lat"=>36.13007667749921,
#         "lng"=>-86.84516327415204,
#         "distance"=>2935,
#         "cc"=>"US",
#         "country"=>"United States"},
#       "categories"=>
#        [{"id"=>"4bf58dd8d48988d1e0931735",
#          "name"=>"Coffee Shop",
#          "pluralName"=>"Coffee Shops",
#          "shortName"=>"Coffee Shop",
#          "icon"=>"https://ss1.4sqi.net/img/categories/food/coffeeshop.png",
#          "parents"=>["Food"],
#          "primary"=>true}],
#       "verified"=>false,
#       "restricted"=>true,
#       "stats"=>{"checkinsCount"=>42, "usersCount"=>20, "tipCount"=>1},
#       "likes"=>{"count"=>0, "groups"=>[]}},
#      {"id"=>"4b100017f964a520446723e3",
#       "name"=>"Starbucks",
#       "contact"=>
#        {"phone"=>"6157811000",
#         "formattedPhone"=>"(615) 781-1000",
#         "twitter"=>"starbucks"},
#       "location"=>
#        {"address"=>"5533 Edmondson Pike",
#         "lat"=>36.041718,
#         "lng"=>-86.745794,
#         "distance"=>12835,
#         "postalCode"=>"37211",
#         "cc"=>"US",
#         "city"=>"Nashville",
#         "state"=>"TN",
#         "country"=>"United States"},
#       "categories"=>
#        [{"id"=>"4bf58dd8d48988d1e0931735",
#          "name"=>"Coffee Shop",
#          "pluralName"=>"Coffee Shops",
#          "shortName"=>"Coffee Shop",
#          "icon"=>"https://ss1.4sqi.net/img/categories/food/coffeeshop.png",
#          "parents"=>["Food"],
#          "primary"=>true}],
#       "verified"=>true,
#       "restricted"=>true,
#       "stats"=>{"checkinsCount"=>6017, "usersCount"=>1348, "tipCount"=>30},
#       "url"=>"http://www.starbucks.com",
#       "likes"=>{"count"=>0, "groups"=>[]},
#       "storeId"=>"8370"},
#      {"id"=>"5299f06211d29a7d156d41c3",
#       "name"=>"Starbucks",
#       "contact"=>{},
#       "location"=>
#        {"lat"=>36.12608780249228,
#         "lng"=>-86.68710155107328,
#         "distance"=>11731,
#         "cc"=>"US",
#         "city"=>"Nashville",
#         "state"=>"TN",
#         "country"=>"United States"},
#       "categories"=>
#        [{"id"=>"4bf58dd8d48988d1e0931735",
#          "name"=>"Coffee Shop",
#          "pluralName"=>"Coffee Shops",
#          "shortName"=>"Coffee Shop",
#          "icon"=>"https://ss1.4sqi.net/img/categories/food/coffeeshop.png",
#          "parents"=>["Food"],
#          "primary"=>true}],
#       "verified"=>false,
#       "restricted"=>true,
#       "stats"=>{"checkinsCount"=>3, "usersCount"=>3, "tipCount"=>0},
#       "likes"=>{"count"=>0, "groups"=>[]}},
#      {"id"=>"4b06d1b7f964a520cef022e3",
#       "name"=>"Starbucks",
#       "contact"=>
#        {"phone"=>"6153765040",
#         "formattedPhone"=>"(615) 376-5040",
#         "twitter"=>"starbucks"},
#       "location"=>
#        {"address"=>"269 Franklin Rd",
#         "lat"=>36.029899,
#         "lng"=>-86.791331,
#         "distance"=>12683,
#         "postalCode"=>"37027",
#         "cc"=>"US",
#         "city"=>"Brentwood",
#         "state"=>"TN",
#         "country"=>"United States"},
#       "categories"=>
#        [{"id"=>"4bf58dd8d48988d1e0931735",
#          "name"=>"Coffee Shop",
#          "pluralName"=>"Coffee Shops",
#          "shortName"=>"Coffee Shop",
#          "icon"=>"https://ss1.4sqi.net/img/categories/food/coffeeshop.png",
#          "parents"=>["Food"],
#          "primary"=>true}],
#       "verified"=>true,
#       "restricted"=>true,
#       "stats"=>{"checkinsCount"=>3607, "usersCount"=>1318, "tipCount"=>13},
#       "url"=>"http://www.starbucks.com",
#       "likes"=>{"count"=>0, "groups"=>[]},
#       "menu"=>
#        {"type"=>"Menu",
#         "label"=>"Menu",
#         "anchor"=>"View Menu",
#         "url"=>
#          "https://foursquare.com/v/starbucks/4b06d1b7f964a520cef022e3/menu",
#         "mobileUrl"=>
#          "https://foursquare.com/v/4b06d1b7f964a520cef022e3/device_menu"},
#       "storeId"=>"8338"},
#      {"id"=>"4f3268d719836c91c7d50478",
#       "name"=>"Starbucks Coffee",
#       "contact"=>{"phone"=>"7706426117", "formattedPhone"=>"(770) 642-6117"},
#       "location"=>
#        {"address"=>"4220 Harding Pike",
#         "lat"=>36.129996,
#         "lng"=>-86.844511,
#         "distance"=>2887,
#         "cc"=>"US",
#         "city"=>"Nashville",
#         "state"=>"TN",
#         "country"=>"United States"},
#       "categories"=>
#        [{"id"=>"4bf58dd8d48988d1e0931735",
#          "name"=>"Coffee Shop",
#          "pluralName"=>"Coffee Shops",
#          "shortName"=>"Coffee Shop",
#          "icon"=>"https://ss1.4sqi.net/img/categories/food/coffeeshop.png",
#          "parents"=>["Food"],
#          "primary"=>true}],
#       "verified"=>false,
#       "restricted"=>true,
#       "stats"=>{"checkinsCount"=>0, "usersCount"=>0, "tipCount"=>0},
#       "url"=>"http://www.starbucks.com",
#       "likes"=>{"count"=>0, "groups"=>[]}}]}]]